const links = [ 'https://f.ua/shop/avtomobilnye-videoregistratory/',
  'https://f.ua/shop/nasosy-i-avtokompressory/24006-naznachenie_dlya-avtomobilya/',
  'https://f.ua/shop/minimojki/',
//   'https://f.ua/shop/avtoholodilniki/',
//   'https://f.ua/shop/avtomobilnye-masla/',
//   'https://f.ua/shop/avtomobilnye-magnitoly/',
//   'https://f.ua/shop/detskie-avtokresla/',
//   'https://f.ua/shop/dvorniki-stekloochistiteli/',
//   'https://f.ua/shop/alko-testery/',
//   'https://f.ua/shop/parktroniki/',
//   'https://f.ua/shop/avtomobilnye-lampy/',
//   'https://f.ua/shop/kanistry-i-lejki-dlya-topliva/',
//   'https://f.ua/shop/minimojki/',
//   'https://f.ua/shop/aksessuary-k-minimojkam/',
//   'https://f.ua/shop/pylesosy/22827-naznachenie_dlya-avtomobilya/',
//   'https://f.ua/shop/avtomobilnaya-akustika/',
//   'https://f.ua/shop/avtomobilnye-usiliteli/',
//   'https://f.ua/shop/shtatnye-avtomagnitoly/',
//   'https://f.ua/shop/aksessuary-dlya-avtomobilnyh-tv-i-monitorov/',
//   'https://f.ua/shop/avtomobilnye-magnitoly/',
//   'https://f.ua/shop/avtomobilnye-monitory-i-tv/',
//   'https://f.ua/shop/avtomobilnye-kondensatory/',
//   'https://f.ua/shop/fm-trasmittery/',
//   'https://f.ua/shop/aksessuary-dlya-podklyucheniya-audio-i-video/',
//   'https://f.ua/shop/ramki-perehodnye/',
//   'https://f.ua/shop/avtomobilnye-antenny/',
//   'https://f.ua/shop/avtomobilnye-videoregistratory/',
//   'https://f.ua/shop/gps-navigatory/',
//   'https://f.ua/shop/avtobezopasnost-i-kontrol/',
//   'https://f.ua/shop/avtosvet/',
//   'https://f.ua/shop/akkumulyatory-i-aksessuary/',
//   'https://f.ua/shop/gromkaya-svyaz-dlya-mobilnyh/',
//   'https://f.ua/shop/avtomobilnye-invertory/',
//   'https://f.ua/shop/alko-testery/',
//   'https://f.ua/shop/razvetviteli-i-perehodniki-prikurivatelya/',
//   'https://f.ua/shop/proektory-na-lobovoe-steklo/',
//   'https://f.ua/shop/avtoskanery/',
//   'https://f.ua/shop/komfort-i-ergonomika/',
//   'https://f.ua/shop/chehly-kovriki-tenty/',
//   'https://f.ua/shop/avtokosmetika/',
//   'https://f.ua/shop/tehpomosch/',
//   'https://f.ua/shop/avtomobilnye-lebedki/',
//   'https://f.ua/shop/naklejki-na-kuzov-avto/',
//   'https://f.ua/shop/shumoizolyaciya/',
//   'https://f.ua/shop/dvorniki-stekloochistiteli/',
//   'https://f.ua/shop/detskie-avtokresla/',
//   'https://f.ua/shop/aksessuary-k-detskim-avtokreslam/',
//   'https://f.ua/shop/avtoshiny/',
//   'https://f.ua/shop/cepi-protivoskolzheniya/',
//   'https://f.ua/shop/chehly-dlya-koles/',
//   'https://f.ua/shop/domkraty/',
//   'https://f.ua/shop/nasosy-i-avtokompressory/24006-naznachenie_dlya-avtomobilya/',
//   'https://f.ua/shop/aksessuary-k-nasosam/',
//   'https://f.ua/shop/manometry-dlya-shin/',
//   'https://f.ua/shop/pistolety-dlya-podkachki-koles/',
//   'https://f.ua/shop/avtomobilnye-akkumulyatory-2579/',
//   'https://f.ua/shop/avtohimiya-prisadki-masla/',
//   'https://f.ua/shop/filtry-maslyanye/',
//   'https://f.ua/shop/filtry-vozdushnye-dvigatelya/',
//   'https://f.ua/shop/filtry-toplivnye/',
//   'https://f.ua/shop/svechi-zazhiganiya/',
//   'https://f.ua/shop/filtry-akpp/',
//   'https://f.ua/shop/steklopodemniki/',
//   'https://f.ua/shop/zaschita-dvigatelya/' 
  ]

module.exports = links;